# Game server config
game:
  tick:
    enabled: true
    periodMs: 50
  
  physics:
    fuelPerSecondAtSpeed1: 0.05
    minSpeed: 0
    maxSpeed: 500
    respawnFuel: 800

  world:
    width: 1000
    height: 1000
    nodes-on-map: 30
    ores:
      iron:
        weight: 100
        value: 10
      gold:
        weight: 20
        value: 50
      diamond:
        weight: 5
        value: 200

      cratecredits:
        weight: 10
        value: 500 # grant 500 credits
      cratefuel:
        weight: 15
        value: 300 # grant 300 fuel

  depots:
    - { id: "d1", x: 200, y: 200, costPerFuel: 0.05, name: "North Outpost" }
    - { id: "d2", x: 800, y: 800, costPerFuel: 0.03, name: "South Outpost" }

# Other stuff
endpoints:
  health:
    enabled: true
    sensitive: false

micronaut:
  serde:
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: basestation
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
