# Game server config
game:
  save-path: "/home/falkensteincy/dev/micronaut-basestation/tmp/gamestate.json"

  tick:
    enabled: true
    periodMs: 50
  
  world:
    width: 1000
    height: 1000
    nodes-on-map: 100
    ores:
      iron:
        weight: 100
        value: 10
      gold:
        weight: 20
        value: 50
      diamond:
        weight: 5
        value: 200

      cratecredits:
        weight: 1
        value: 1500

  depots:
    - { id: "d1", x: 200, y: 200, costPerFuel: 0.05, name: "North Outpost" }
    - { id: "d2", x: 800, y: 800, costPerFuel: 0.03, name: "South Outpost" }

  mission-providers:
    poll-interval-ms: 3000
    timeout-ms: 5000
    completion-path: "/complete"
    urls:
      - http://127.0.0.1:8081/missions

# Other stuff
endpoints:
  health:
    enabled: true
    sensitive: false

micronaut:
  serde:
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: basestation
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
